import { Link } from "wouter";

// Design: Blue & White financial services theme — Montserrat headings, Nunito Sans body
// Clean legal document layout with sticky back-to-top nav and branded header

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white">
      {/* Top Nav Bar */}
      <nav className="sticky top-0 z-50 bg-white border-b border-slate-100 shadow-sm">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/">
            <span
              className="text-blue-700 font-bold text-lg cursor-pointer hover:text-blue-800 transition-colors flex items-center gap-2"
              style={{ fontFamily: "Montserrat, sans-serif" }}
            >
              ← Back to Arise Credit Pro
            </span>
          </Link>
          <span
            className="text-slate-400 text-sm"
            style={{ fontFamily: "Nunito Sans, sans-serif" }}
          >
            Last updated: May 11, 2026
          </span>
        </div>
      </nav>

      {/* Hero Header */}
      <div className="bg-gradient-to-r from-blue-700 to-blue-500 py-14 px-6 text-center">
        <h1
          className="text-4xl md:text-5xl font-extrabold text-white mb-3"
          style={{ fontFamily: "Montserrat, sans-serif" }}
        >
          Privacy Policy
        </h1>
        <p
          className="text-blue-100 text-lg max-w-2xl mx-auto"
          style={{ fontFamily: "Nunito Sans, sans-serif" }}
        >
          Arise Credit Pro — East Consulting LLC
        </p>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-14">
        <div
          className="prose prose-slate max-w-none"
          style={{ fontFamily: "Nunito Sans, sans-serif", lineHeight: "1.8" }}
        >
          <p className="text-slate-600 text-base mb-8">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          {/* Section */}
          <Section title="Interpretation and Definitions">
            <SubSection title="Interpretation">
              <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            </SubSection>
            <SubSection title="Definitions">
              <p>For the purposes of this Privacy Policy:</p>
              <ul>
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to East Consulting LLC, 850 N Jefferson St.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong>Country</strong> refers to: Mississippi, United States</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
                <li><strong>Service</strong> refers to the Website.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>Website</strong> refers to Arise Credit Pro, accessible from <a href="http://www.arisecreditpro.com" className="text-blue-600 hover:underline">http://www.arisecreditpro.com</a>.</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </SubSection>
          </Section>

          <Section title="Collecting and Using Your Personal Data">
            <SubSection title="Types of Data Collected">
              <p><strong>Personal Data</strong></p>
              <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
              <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
              </ul>
              <p><strong>Usage Data</strong></p>
              <p>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
              <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            </SubSection>
            <SubSection title="Tracking Technologies and Cookies">
              <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
              <ul>
                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
              </ul>
              <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
              <p>Where required by law, we use non-essential cookies only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings.</p>
              <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
              <ul>
                <li><strong>Necessary / Essential Cookies</strong> — Type: Session Cookies. Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
                <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> — Type: Persistent Cookies. Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
                <li><strong>Functionality Cookies</strong> — Type: Persistent Cookies. Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
              </ul>
            </SubSection>
            <SubSection title="Use of Your Personal Data">
              <p>The Company may use Personal Data for the following purposes:</p>
              <ul>
                <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                <li><strong>To provide You with news, special offers, and general information</strong> about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about.</li>
                <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns.</li>
              </ul>
              <p>We may share Your Personal Data in the following situations:</p>
              <ul>
                <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with any merger, sale of Company assets, financing, or acquisition.</li>
                <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
                <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
                <li><strong>With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
              </ul>
            </SubSection>
            <SubSection title="Retention of Your Personal Data">
              <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
              <p>We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
              <ul>
                <li><strong>Account Information:</strong> Retained for the duration of your account relationship plus up to 24 months after account closure.</li>
                <li><strong>Customer Support Data:</strong> Support tickets and correspondence up to 24 months from the date of ticket closure.</li>
                <li><strong>Usage Data:</strong> Website analytics data up to 24 months from the date of collection. Server logs up to 24 months for security monitoring.</li>
              </ul>
            </SubSection>
          </Section>

          <Section title="Transfer of Your Personal Data">
            <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
            <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place.</p>
          </Section>

          <Section title="Delete Your Personal Data">
            <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.</p>
            <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>
            <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
          </Section>

          <Section title="Disclosure of Your Personal Data">
            <SubSection title="Business Transactions">
              <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
            </SubSection>
            <SubSection title="Law Enforcement">
              <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            </SubSection>
            <SubSection title="Other Legal Requirements">
              <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
              <ul>
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>Protect the personal safety of Users of the Service or the public</li>
                <li>Protect against legal liability</li>
              </ul>
            </SubSection>
          </Section>

          <Section title="Security of Your Personal Data">
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          </Section>

          <Section title="Children's Privacy">
            <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>
          </Section>

          <Section title="Links to Other Websites">
            <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          </Section>

          <Section title="Changes to this Privacy Policy">
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          </Section>

          <Section title="Contact Us">
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
              <li>By email: <a href="mailto:support@arisecreditpro.com" className="text-blue-600 hover:underline">support@arisecreditpro.com</a></li>
            </ul>
          </Section>
        </div>

        {/* Back to top */}
        <div className="mt-16 pt-8 border-t border-slate-100 text-center">
          <Link href="/">
            <span
              className="inline-block bg-blue-600 text-white font-bold px-8 py-3 rounded-full hover:bg-blue-700 transition-colors cursor-pointer"
              style={{ fontFamily: "Montserrat, sans-serif" }}
            >
              ← Back to Home
            </span>
          </Link>
        </div>
      </div>

      {/* Footer */}
      <div className="bg-slate-900 text-slate-400 text-center py-6 text-sm" style={{ fontFamily: "Nunito Sans, sans-serif" }}>
        © 2026 Arise Credit Pro. All rights reserved.
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2
        className="text-2xl font-bold text-slate-900 mb-4 pb-2 border-b-2 border-blue-100"
        style={{ fontFamily: "Montserrat, sans-serif" }}
      >
        {title}
      </h2>
      <div className="text-slate-600 space-y-3">{children}</div>
    </div>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-5">
      <h3
        className="text-lg font-semibold text-slate-800 mb-2"
        style={{ fontFamily: "Montserrat, sans-serif" }}
      >
        {title}
      </h3>
      <div className="text-slate-600 space-y-2">{children}</div>
    </div>
  );
}
